// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF09f0c1hx8VdwLR1XHGhTi9PtVk7FzeI',
    appId: '1:850122133212:android:d5f37bf94e7fa99b4b2e19',
    messagingSenderId: '850122133212',
    projectId: 'foodorderingapp-f4347',
    databaseURL: 'https://foodorderingapp-f4347-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodorderingapp-f4347.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAISIdouGVpfgWXvm2ynVV2uqf7KtTeBk',
    appId: '1:850122133212:ios:a1f33d0a1115a4974b2e19',
    messagingSenderId: '850122133212',
    projectId: 'foodorderingapp-f4347',
    databaseURL: 'https://foodorderingapp-f4347-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodorderingapp-f4347.appspot.com',
    androidClientId: '850122133212-iol30kjqdtp56t9570l3abc9cl4jqqrg.apps.googleusercontent.com',
    iosClientId: '850122133212-kb4ot5qnvrlg6jvhdoe35bp56maelb8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodFinal',
  );
}
